version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: like_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: like_redis
    ports:
      - "6379:6379"